default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: game_statistics_api_development

test:
  <<: *default
  database: game_statistics_api_test

production:
  <<: *default
  database: game_statistics_api_production
  username: game_statistics_api
  password: <%= ENV['GAME_STATISTICS_API_DATABASE_PASSWORD'] %>
